seed: 42 # rastgelelik sabitleniyor, her calistirmada ayni sonuclar elde edilir
task: "multiclass" # birden fazla class yapilcak

data:
  train_path: "data/processed/merged_clean.parquet"
  test_size: 0.2 # verinin %20'si test olacak
  label_col: "attack_type" # modelin tahmin edecegi sutun

model:
  n_d: 32 # model katmaninda kac tane ogrenme hucresi (laten feature) olacak
  n_a: 32 # modelin attention kismindaki hucre sayisi 
  n_steps: 5 # model bir veriyi islerken kac adimda karar verecek
  gamma: 1.5 # her adimin sonucunu ne kadar etkili yapacagini belirler
  lambda_sparse: 1e-4 # modelin gereksiz konulara zaman harcamamasi
  mask_type: "entmax" # modelin dikkat mekanizmasi tipi yumusak daha dengeli olsun

train:
  max_epochs: 100 # model verinin uzerinden 100 kez gececek
  patience: 10 # 10 tur boyunca gelisme olmazsa egitimi durdur
  batch_size: 2048 # her adimda 2048 ornegi birlikte isle
  virtual_batch_size: 256 # bellek az ise 256'lik kucuk parcalaara bol sirayla isle
  lr: 0.02 # ogrenme hizi

metrics:
  watch: "f1_macro" # F1 makro ortalamasi
  eval_set: "validation" # model performansi validation uzerinden olculecek.
